
In order to successfully complete this assignment we recommend that you participate both individually and in groups during class. **Turn in your assignment using D2L no later than 11:59pm on the day of class.** Grading is based on correctness and completion.

## Put the names of all group members present today below:




In [ ]:
print("Names: Fangjun Huang, Benjamin Maves, Aryan Sharma")

Names: Fangjun Huang, Benjamin Maves, Aryan Sharma


# 02 In-Class Assignment: Vectors


### Objectives

1. Be able to work with different representations of vectors in Python and know the implications of using each - tuple, list, numpy array, etc.
2.  Know what types of operations are valid in the vector space $\mathbb R^n$.
3. Be able to express a given vector as a linear combination of given vectors or determine if this is impossible.


### Agenda for today's class (80 minutes)

1. [(30 minutes) Review pre-class assignment](#Pre-class_assignment_review) - discuss vector spaces, linear combinations, and graphical interpretation of vector addition and scalar multiplication in $\mathbb R^2$.
1. [(40 minutes) Vectors in Python](#Vectors_in_Python)
1. [(10 minutes) Linear Combinations Relation to Linear Systems](#Linear_comb_sys)

---
<a name="Pre-class_assignment_review"></a>
## 1. Pre-class assignment review



### Vector Addition Properties
For any vectors ```x```, ```y```, and ```z``` of the same size/dimension, we have the following properties:
1. Vector addition is commutative: ```x + y = y + x```.
1. Vector addition is associative: ```(x + y) + z = x + (y + z)```. We can therefore write both as ```x + y + z```.
1. Adding the zero vector to a vector results in the original vector: ```x + 0 = 0 + x = x```.  (This is an example where the size of the zero vector follows from the context, i.e., its size must be the same as the size of ```x```)
1. ```x − x = 0```. Subtracting a vector from itself yields the zero vector. (Here too the size of 0 is the size of ```x```.)


### Scalar-Vector Multiply Properties
For any vectors ```x```, ```y```, and scalars ```a```, ```b```, we have the following properties

* Scalar-vector multiply is commutative: ``` ax  = x * a```; This means that scalar-vector multiplication can be written in either order.
* Scalar-vector multiply is associative: ```(ab)x = a(bx)``` 
* Scalar-vector multiply is distributive: ```a(x + y) = ax + ay```, ```(x+y)a = xa + ya```, and ```(a+b)x = ax + bx```.

&#9989; **<font color=red>DO THIS:</font>**  Discuss which of the following operations are valid operations in Linear Algebra. In the case when an operation is well defined, determine the result. In the case when an operation is not well defined, explain why.

* $(-\pi, 3, \sqrt{2}) + \pi$
* $(-\pi, 3, \sqrt{2}) + (0,1,2)$
* $\pi(7,2) + 3(0,0,0)$
* $\pi(7,2,0) + 3(0,0,0)$
* $2/(1,1,1)$
* $(1,1,1)/2$

Put your answer here:
* Not defined cannot add scalar and vector
* $(-\pi, 4, \sqrt{2})$
* NOt defined cannot add vectors of different dimmensions
* $(7\pi,2\pi,0) $
* NOt defined cannot divide scalar by vector
* $(\frac{1}{2},\frac{1}{2},\frac{1}{2})$


Note that we have not defined multiplication of two vectors yet! Soon we will define the dot product of two vectors of the same dimension, the result of which will be a scalar. 

### Linear Combinations 

Let $x$ and $y$ be two n-dimesional vectors. We can define the **linear combination** of these two vectors as $ax + by$ where $a$ and $b$ are scalar coefficients. Since a vector space is closed under addition and scalar multipication, it is closed under linear combitations. **Explain why!**


&#9989; **<font color=red>DO THIS:</font>**  Express the following as linear combinations of the vectors $x$ and $y$, i.e., find the coefficients $a$ and $b$ in the linear combination $ax + by$.

* $x+y$
* $x-y$
* $3x$
* $y/2$

* $x+y: a=1, b=1$
* $x-y: a=1, b=-1$
* $3x:  a=3, b=0$
* $y/2: a=0, b=1/2$

---
<a name="Vectors_in_Python"></a>

## 2. Vectors in Python


For those who are new to Python, there are many common mistakes that can happen in this course. Try to fix the following codes.


### SyntaxError   
It means that the code does not make sense in Python. We would like to define a vector with four numbers.

&#9989; **<font color=red>DO THIS:</font>** Fix the following code to create three vectors with four numbers.

In [ ]:
x = [1, 2, 3.4, 4]
y = [1, 2, 3, 5]
z = [1, 2, 3, 6.3]

Although you may have been able to get rid of the error messages the answer to your problem may still not be correct.  Throughout the semester we will be using a Python program called ```answercheck``` to allow you to check some of your answers.  This program doesn't tell you the right answer but it is intended to be used as a way to get immediate feedback and accelerate learning.

&#9989; **<font color=red>DO THIS:</font>** First we will need to download ```answercheck.py``` to your current working directory.  You only really need to do this once.  However, if you delete this file by mistake sometime during the semester, you can come back to this notebook and download it again by running the following cell:

In [ ]:
from urllib.request import urlretrieve

urlretrieve('https://raw.githubusercontent.com/colbrydi/jupytercheck/master/answercheck.py', 
            'answercheck.py');

&#9989; **<font color=red>DO THIS:</font>** Just run the following command to see if you got ```x```, ```y``` and ```z``` correct when you fixed the code above. 

In [ ]:
from answercheck import checkanswer

checkanswer([x,y,z],'e80321644979a873b273aebbbcd0e450');

Testing [[1, 2, 3.4, 4], [1, 2, 3, 5], [1, 2, 3, 6.3]]
Answer seems to be correct



**_NOTE_** make sure you do not change the ```checkanswer``` commands.  The long string with numbers and letters is the secret code that encodes the true answer.  This code is also called the HASH.  Feel free to look at the ```answercheck.py``` code and see if you can figure out how it works?  


### Numpy   
Numpy is a common way to represent vectors, and you are suggested to use ```numpy``` unless otherwise specified. The benefit of ```numpy``` is that it can perform the linear algebra operations listed in the previous section.  

For example, the following code uses ```numpy.array``` to define a vector of four elements.

In [ ]:
import numpy as np
x_np = np.array([-1, 0, 2, 3.1])
x_np

array([-1. ,  0. ,  2. ,  3.1])

#### Scalars versus 1-vectors
In mathematics, 1-vector is considered as a scalar. But in Python, they are not the same. 

In [ ]:
x = 2.4
y = [2.4]
x == y

False

In [ ]:
x == y[0]

True

#### Lists of vectors 
We can have a list of numpy arrays or a list of lists. In this case, the vectors can have different dimensions. 

&#9989; **<font color=red>DO THIS:</font>** Modify the print statement using indexing to only print the value 3 from the ```list_of_vectors``` defined below. 

In [ ]:
x_np = np.array([-1,0, 2, 3.1])
y_np = np.array([1,-1,3])
z_np = np.array([0,1])
list_of_vectors = [x_np,y_np,z_np]

print(list_of_vectors[1][2])

NameError: name 'np' is not defined


#### Indexing   
The index of a vector runs from 0 to $n-1$ for a $n$-vector.

&#9989; **<font color=red>DO THIS:</font>**  The following code tries to get the third element of ```x_np```, which is the number ```2.0```. Fix this code to provide the correct answer.

In [ ]:
print(x_np[2])

2.0


&#9989; **<font color=red>DO THIS:</font>**  Replace only the third element of ```x_np``` with the number ```20.0``` such that the new values of ```x_np``` is [-1, 0, 20., 3.1]

In [ ]:
# Replace the third element using 20.0, then the resulting element is 
#####Start your code here #####
x_np[2] = 20
#####End of your code here#####
print(x_np)


[-1.   0.  20.   3.1]


In [ ]:
from answercheck import checkanswer

checkanswer(x_np,'993d5cbc6ddeb10776ed48159780a5d3');

Testing [-1.   0.  20.   3.1]
Answer seems to be correct



There is a special index -1, which represents the last element in an array. 
There are several ways to get more than one consecutive element. 
+ x_np[1:3] gives the 2nd and 3rd elements only. It starts with the first index and ends before the second index. So the number of element is just the difference between these two numbers.  
+ x_np[1:-1] is the same as x_np[1:3] for a 4-vector.
+ If you want the last element also, then you do not need to put the index, e.g., x_n[1:] gives all elements except the first one. You can do the same thing as the first one. 


&#9989; **<font color=red>DO THIS:</font>** you are given a vector (```x_np```) of $n$ elements, define a new vector (```d```) of size $n-1$ such that $d_i = x_{i+1}-x_i$ for $i=1,\dots,n-1$.  **_Hint_** try doing this without writing your own loop.  You should be able to use simple ```numpy``` indexing as described above. 

In [ ]:
x_np = np.array([1,8,3,2,1,9,7])

## Put your answer to the above question here.
d = x_np[1:]- x_np[0:-1]
d

array([ 7, -5, -1, -1,  8, -2])

In [ ]:
from answercheck import checkanswer

checkanswer(d,'14205415f0ed56e608d0a87e7253fa70');

Testing [ 7 -5 -1 -1  8 -2]
Answer seems to be correct



### Vector equality in numpy and list

The relational operator (```==```, ```<```, ```>```, ```!=```, etc.) can be used to check whether the vectors are the same or not. However, they will act differently if the code is comparing ```numpy.array``` objects or a ```list```. For example, in ```numpy```,  ```==``` checks whether the corresponding elements in the ```array```are equal and returns an array whose components have True or False values. For ```list```, ```==``` checks whether the corresponding components in the two lists are equal and returns a single True or False value.  The result will be true only if **all** components in the first list are equal to the corresponding components in the second list.

In [ ]:
x = [-1, 0, 2, 3.1]
y = x.copy()
y[2] = 20.2

x_np = np.array(x)
y_np = np.array(y)

In [ ]:
x == y

False

In [ ]:
np.array(x_np) == np.array(y_np)

array([ True,  True, False,  True])

### Zero vectors and Ones vectors in numpy

+ np.zeros(n) creates a vector of size n with all 0s
+ np.ones(n) creates a vector of size n with all 1s

&#9989; **<font color=red>DO THIS:</font>** Create a zero vector (called ```zero_np```) with the same dimension as vector ```x_np```. Create a ones vector (called ```ones_np```) also with the same dimension as vector ```x_np```. 

In [ ]:
x_np = np.array([-1, 0, 2, 3.1])
### Define zero_np and ones_np here 
zero_np = np.zeros(np.shape(x_np))
ones_np = np.ones(np.shape(x_np))

In [ ]:
from answercheck import checkanswer

checkanswer([zero_np, ones_np],'7f874c2e446786655ff96f0bbae8a0c6');

Testing [array([0., 0., 0., 0.]), array([1., 1., 1., 1.])]
Answer seems to be correct



### Vector addition and subtraction
In this section, you will understand why we use numpy for linear algebra operations. If x and y are numpy arrays of the same size, we can have x + y and x-y for their addition and subtraction, respectively.

In [ ]:
x_np = np.array([1,2,3])
y_np = np.array([100,200,300])

v_sum = x_np + y_np
v_diff = x_np - y_np

print (f'Sum of vectors: {v_sum}')
print (f'Difference of vectors: {v_diff}')

Sum of vectors: [101 202 303]
Difference of vectors: [ -99 -198 -297]


For comparison, we also put the addition of two lists below. Recall from the pre-class assignment, we have to define a function to add two lists for linear algebra. 


&#9989; **<font color=red>DO THIS:</font>**  Modify the following code to properly add and subtract the two lists.  You can copy the relevant code from the pre-class assignment.

In [ ]:
x = [1,2,3]
y = [100,200,300]

v_sum=[]
v_diff = []
for i in range(len(x)):
    v_sum.append(x[i]+y[i])
    v_diff.append(x[i]-y[i])

print (f'Sum of vectors: {v_sum}')
print (f'Difference of vectors: {v_diff}')

Sum of vectors: [101, 202, 303]
Difference of vectors: [-99, -198, -297]


### Scalar-vector addition in Python (not in LA!)
A scalar-vector addition means that the scalar (or a 1-vector) is added to all elements of the vector. Note that this is **not a valid operation in Linear Algebra**, meaning that if

$$v=(1,2,3)$$ 

is a given vector, then 

<font color=red>$$v+5$$</font>

is not well defined! However, 

$$v+(5,5,5)$$

is well defined.

&#9989; **<font color=red>DO THIS:</font>** Add a scalar 20.20 to all elements of the following vector ```x_np ``` and store the result back into ```x_np```

In [ ]:
x_np = np.array([1.0,2.0,3.0])
x_np = x_np +20.20

In [ ]:
from answercheck import checkanswer

checkanswer(x_np,'2f8cbcce405fa12b8608422ff28544bb');

Testing [21.2 22.2 23.2]
Answer seems to be correct



### Linear combination with Numpy

In the following example, we are given two vectors (```x_np``` and ```y_np```), and two scalars (```alpha``` and ```beta```), we obtain the linear combination ```alpha*x_np + beta*y_np```.

In [ ]:
x_np = np.array([1,2])
y_np = np.array([3,4])
alpha = 0.5
beta = -0.8
c = alpha*x_np + beta*y_np
print(c)

[-1.9 -2.2]


We can also define a function ```lincomb``` to perform the linear combination. 

&#9989; **<font color=red>DO THIS:</font>** Finish the following code for lincomb and compare the results we just get.

In [ ]:
def lincomb(coef, vectors): 
    n = len(vectors[0])  # get the dimension of the vectors. note they have to be of the same dimension
    comb = np.zeros(n)   # initial the value with all zeros.
    comb = coef[0]*vectors[0] + coef[1]*vectors[1]
    ### Add code here to calculate the linear combination of the input vecotrs and the coefficients. 
    ### Note that the number of elements in coef should be equal to the number of elements in vectors
    return comb

In [ ]:
from answercheck import checkanswer

combination = lincomb([alpha, beta], [x_np,y_np])

checkanswer(combination,'8bab7329c94f3e3cda423add411685c2');

Testing [-1.9 -2.2]
Answer seems to be correct



We can also test the functions ourselves by using values for which we know the answer. For example, the following tests are multiplying by the zero scalars and adding the zero vector - we know what these answers should be and can check them.

In [ ]:
combination = lincomb([0, 0], [x_np,y_np])

combination == np.zeros(combination.shape)


array([ True,  True])

In [ ]:
combination = lincomb([2, 2], [combination,np.zeros(combination.shape)])

combination == 2*combination

array([ True,  True])

If you want to check that all values in a ```numpy.array``` are the same you could convert it to a list or there is a method called ```alltrue``` which checks if everything is true. It is a good idea to use this method if vectors get big. 

In [ ]:
combination = lincomb([2, 2], [combination,np.zeros(combination.shape)])

np.alltrue(combination == 2*combination)

True

---
<a name="Linear_comb_sys"></a>

## 3. Linear Combinations Relation to Linear Systems

- [03--Linear_comb_sys.ipynb](03--Linear_comb_sys.ipynb)

In the following example we will start exploring the relationship between linear combinations of vectors and finding a solution of a linear system. 

&#9989; **<font color=red>DO THIS:</font>** Given the following vectors $\mathbf u$, $\mathbf v$, and $\mathbf b$, find scalars $x$ and $y$, so that $x \mathbf u+y\mathbf v=\mathbf b$. In other words, we are trying to express the vector $\mathbf b$ as a linear combination of the vectors $\mathbf u$ and $\mathbf v$. If the request is possible, find the values of $x$ and $y$ that satisfy it and state if they are unique. If it is impossible, explain why. It may be helpful to represent the vectors graphically.

* $\mathbf u = \left[\begin{array}{rr}1 \\ 1\end{array}\right], \qquad \mathbf v = \left[\begin{array}{rr}1 \\ -1\end{array}\right], \qquad \mathbf b = \left[\begin{array}{rr}3 \\ 5\end{array}\right]$
* $\mathbf u = \left[\begin{array}{rr}1 \\ 2\end{array}\right], \qquad \mathbf v = \left[\begin{array}{rr}-2 \\ -4\end{array}\right], \qquad \mathbf b = \left[\begin{array}{rr}3 \\ 6\end{array}\right]$
* $\mathbf u = \left[\begin{array}{rr}1 \\ 2\end{array}\right], \qquad \mathbf v = \left[\begin{array}{rr}-2 \\ -4\end{array}\right], \qquad \mathbf b = \left[\begin{array}{rr}3 \\ 5\end{array}\right]$


1. x=4, y=-1
2. Incompatible because they are parallel and never intersect
3. Incompatable because they are parallel and dont intersect

Below is a similar problem, but this time we approach it graphically.

&#9989; **<font color=red>DO THIS:</font>** Use [the following Desmos link](https://www.desmos.com/calculator/vyo5elivb9) to gain a visual understanding of liner combinations in $\mathbb R^2$.

----
Written by Dr. Dirk Colbry, Michigan State University and Dr. Ming Yan, Michigan State University<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=d305643f-c00c-4985-a40d-dcbee1f47f30' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>