### Put the names of all group members present today below:

David Robbins, Jacob Miller, Christian Lulaj, Kaitlyn Watson

# 12 In-Class Assignment: Vector Spaces

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/3d_basis_transformation.svg/580px-3d_basis_transformation.svg.png" width="50%">

Image from: [https://en.wikipedia.org/wiki/Change_of_basis](https://en.wikipedia.org/wiki/Change_of_basis)



    

### Objectives
1. Be able to state key definitions like span, basis, and linear dependence/independence.
1. Determine if a set of vectors
 - Spans a given space
 - Is linearly independent
 - Is a basis for a given space
1. Understand the axioms for vector spaces (you do not need to memorize them though), determine if a given axiom is satisfied.
1. Familiarize yourself with interesting types of vector spaces (matrices, functions, $\mathbb C^n$). 
1.  Remember that the following statements are equivalent 
 - The column vectors of $A$ form a basis for $\mathbb R^n$
 - $|A| \ne 0$
 - $A$ is invertible.
 - $A$ is row equivalent to $I_n$ (i.e. its reduced row echelon form is $I_n$)
 - The system of equations $Ax = b$ has a unique solution.
 - $rank(A) = n$
1. Be able to determine if a set of vectors is a subspace of a given vector space.

### Agenda for today's class (80 minutes)

1. (20 minutes) [Review Pre-Class Assignment](#Review)
2. (20 minutes) [Introduction to subspaces](#Introduction-to-subspaces)
3. (20 minutes) [Basis Vectors](#Basis-Vectors)
4. (20 minutes) [Vector Spaces](#Vector-Spaces)



----

<a name="Review"></a>

## 1. Review Pre-class Assignment




---
<a name=Introduction-to-subspaces></a>
## 2. Introduction to subspaces





---
<a name=Basis-Vectors></a>
## 3. Basis Vectors



Consider the following example. We claim that the following set of vectors form a basis for $\mathbb R^3$:

$$B = \{(2,1, 3), (-1,6, 0), (3, 4, -10) \}$$

If these vectors form a basis they must be _**linearly independent**_ and _**Span**_ the entire space of $\mathbb R^3$

In [ ]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

&#9989; **<font color=red>DO THIS:</font>** Create a $3 \times 3$ numpy matrix $A$ where the columns of $A$ form the basis vectors. 

In [ ]:
#Put your answer to the above question here

A=np.matrix([[2,-1,3], [1,6,4], [3,0,-10]])

A


matrix([[  2,  -1,   3],
        [  1,   6,   4],
        [  3,   0, -10]])

In [ ]:
from answercheck import checkanswer

checkanswer.matrix(A,'68b81f1c1041158b519936cb1a2e4d6b');


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[  2.  -1.   3.]
 [  1.   6.   4.]
 [  3.   0. -10.]]
Answer seems to be correct



&#9989; **<font color=red>DO THIS:</font>** Using python, calculate the determinant of matrix $A$.

In [ ]:
# Put your answer to the above question here. 
detA = np.linalg.det(A)
print(detA)

-196.00000000000009


&#9989; **<font color=red>DO THIS:</font>** Using python, calculate the inverse of $A$.

In [ ]:
# Put your answer to the above question here.

A_inv=np.linalg.inv(A)
print(A_inv)

[[ 0.30612245  0.05102041  0.1122449 ]
 [-0.1122449   0.14795918  0.0255102 ]
 [ 0.09183673  0.01530612 -0.06632653]]


&#9989; **<font color=red>DO THIS:</font>** Using python, calculate the rank of $A$.

In [ ]:
# Put your answer to the above question here.
rankA = np.linalg.matrix_rank(A)
print(rankA)

3


&#9989; **<font color=red>DO THIS:</font>** Using python, calculate the reduced row echelon form of $A$.

In [ ]:
# Put your answer to the above question here. 
rref = sym.Matrix(A).rref()[0]
rref

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

&#9989; **<font color=red>DO THIS:</font>** Using the above $A$ and the vector $b=(1,3,2)$.  What is the solution to $Ax=b$?  

In [ ]:
#Put your answer to the above question here.
b=np.matrix([[1],[3],[2]])

x=A_inv*b
print(x)

[[0.68367347]
 [0.38265306]
 [0.00510204]]


In [ ]:
from answercheck import checkanswer

checkanswer.matrix(x,'8b0938260dfeaafc9f8e9fec0bc72f17');

Testing [[0.68367]
 [0.38265]
 [0.0051 ]]
Answer seems to be correct



Turns out a matrix where column vectors are formed from basis vectors has a lot of interesting properties and the following statements are equivalent, meaning that if one of these bullet points is satisfied then the rest are as well and if one is not true, then the rest are not true as well.

- The column vectors of $A$ form a basis for $\mathbb R^n$
- $|A| \ne 0$
- $A$ is invertible.
- $A$ is row equivalent to $I_n$ (i.e. its reduced row echelon form is $I_n$)
- The system of equations $Ax = b$ has a unique solution.
- $rank(A) = n$




---
<a name=Vector-Spaces></a>
## 4. Vector Spaces

A **Vector Space** is a set $V$ of elements called **vectors**, having operations of addition and scalar multiplication defined on it that satisfy the following conditions ($u$, $v$, and $w$ are arbitrary elements of $V$, and c and d are scalars.)

### Closure Axioms

1. The sum $u + v$ exists and is an element of $V$. ($V$ is closed under addition.)
2. $cu$ is an element of $V$. ($V$ is closed under scalar multiplication.)

### Addition Axioms

3. $u + v = v + u$ (commutative property)
4. $u + (v + w) = (u + v) + w$ (associative property)
5. There exists an element of $V$, called a **zero vector**, denoted $0$, such that $u+0 = u$
6. For every element $u$ of $V$, there exists an element called a **negative** of $u$, denoted $-u$, such that $u + (-u) = 0$.

### Scalar Multiplication Axioms

7. $c(u+v) = cu + cv$
8. $(c + d)u = cu + du$
9.  $c(du) = (cd)u$
10. $1u = u$

### Definition of a basis of a vector space

> A finite set of vectors ${v_1,\dots, v_n}$ is called a **basis** of a *vector space* $V$ if the set *spans* $V$ and is *linearly independent*. 
>i.e. each vector in $V$ can be expressed uniquely as a *linear combination* of the vectors in a basis.



## Vector spaces

&#9989; **<font color=red>DO THIS:</font>** Let $U$ be the set of all circles in $\mathbb R^2$ having center at the origin. 
Interpret the origin as being in this set, i.e., it is a circle centered at the origin with radius zero. 
Assume $C_1$ and $C_2$ are elements of $U$. 
Let $C_1 + C_2$ be the circle centered at the origin, whose radius is the sum of the radii of $C_1$ and $C_2$. 
Let $kC_1$ be the circle centered at the origin, whose radius is $|k|$ times that of $C_1$. 
Determine which vector space axioms hold and which do not. 


CLOSURE:

1.<br/>
By defintion of addition $C_{r_1} + C_{r_2} = C_{r_1+r_2}$ 

2.<br/>
For some $k \in \mathbb{R} $ and $C_{r_1} \in \mathbb{U} $, $k*C_{r_1} = C_{|k|*r_1}$, because $C_{r_1}$ is centered at the origin, $C_{|k|*r_1}$ is also centered at the origin and thus, $C_{|k|*r_1} \in \mathbb{U}$ by definition of scalar multiplication under $\mathbb{U}$.

ADDITION:

3.<br/>
Let $C_{r_1}, C_{r_2} \in \mathbb{U}$ then, by definition $ C_{r_1} +  C_{r_2} =  C_{r_1 + r_2}$ <br/> $\implies$ $ C_{r_1 + r_2} = C_{r_2 + r_1} $ <br />
$\implies$ $ C_{r_2} +  C_{r_1} $

4.<br/>
Let $C_{r_1}, C_{r_2}, C_{r_3} \in \mathbb{U}$ <br/>
$C_{r_1} +(C_{r_2}+ C_{r_3})  = C_{r_1} +(C_{r_2 + r_3}) = C_{r_1 + (r_2 + r_3)}$<br/>
$\implies  C_{(r_1 + r_2) + r_3}$<br/>
$\implies (C_{r_1} + C_{r_2} )+C_{r_3}$ 

5.<br/>
Let $k = 0$ then by definition $0*C_{r1} = C_{0 * r1} = C_{0}$<br/>
For any $C_{r}$, $C_{r} + C_{0} = C_{r + 0} = C_{r}$, thus there exists zero element in $\mathbb{U}$.

6.<br/>There is no elements with a negative radius, thus there is no additive inverse.

MULTIPLICATION:

7.<br/>
For some $k \in \mathbb{R}$ and $C_r,C_b \in \mathbb{U}$.<br/> Then $k*(C_r+C_b) = k*C_{r+b} = C_{|k|*(r+b)} = C_{|k|*r+|k|*b} = k*C_r+k*C_b$

8.<br/>
Let $k,c \in \mathbb{R}$ and $C_r \in \mathbb{U}$ then $(k + c) * C_r = C_{|k + c| * r} = C_{|k + c| * r}$<br/>
Under the case that k or c are exclusively negative, this axiom does not hold as we cannot break up the absolute value.

9.<br/>
Let $k,c \in \mathbb{R}$ and $C_r \in \mathbb{U}$ then $k*(c*C_r) = k*C_{|c|*r} = C_{|k|(|c|*r)} = C_{(|k||c|)*r} = (k*c)C_{r}$

10.<br/>
Let $1\in \mathbb{R}$ be the identity element, then for any $C_r \in \mathbb{U}$ $1*C_r = C_{1*r} = C_r$.


### Spans:

&#9989; **<font color=red>DO THIS:</font>** Let $v$, $v_1$, and $v_2$ be vectors in a vector space $V$. 
Let $v$ be a linear combination of $v_1$ and $v_2$. 
If $c_1$ and $c_2$ are nonzero real numbers, show that $v$ is also a linear combination of $c_1v_1$ and $c_2v_2$.

$v = a * v_1 + b * v_2$ for some $a,b \in \mathbb{R}$.<br/>

Also, $v = k_1 *(c_1* v_1)  + k_2 *(c_2* v_2)$ for some $k_1,k_2, c_1, c_2 \in \mathbb{R}$ where $ c_1, c_2 $ 
not equal to zero.<br/>

Then, $a=k_1*c_1$ and $b=k_2*c_2$<br/>
Thus, $k_1 = \frac{a}{c_1}$ and $k_2 = \frac{b}{c_2}$

&#9989; **<font color=red>DO THIS:</font>** Let $v_1$ and $v_2$ span a vector space $V$. 
Let $v_3$ be any other vector in $V$. 
Show that $v_1$, $v_2$, and $v_3$ also span $V$.

Because $v_1,v_2$ span $V$, for any vector $v\in V$ <br/>$v = c_1*v_1 +c_2*v_2$<br/>
So for a vector $v_3$, given any vector $u$ in $V$, $u = c_1*v_1 +c_2*v_2 + c_3 *v_3$.

### Linear Independent:
Consider the following matrix, which is in the reduced row echelon form.


$$ 
\left[
\begin{matrix}
    1   & 0 & 0 & 7  \\
    0   & 1 & 0 & 4  \\
    0   & 0 & 1 & 3
\end{matrix}
\right] 
$$

&#9989; **<font color=red>DO THIS:</font>** Show that the row vectors form a linearly independent set:


By definition, if a RREF matrix has all leading ones, it is therefore linearly independent. Therefore, the matrix and the vectors above must be linearly independent as there are no free variables and all leading ones.

&#9989; **<font color=red>DO THIS:</font>** Is the set of nonzero row vectors of any matrix in reduced row echelon form linearly independent? Discuss in your groups and include your thoughts below.

Yes, because in order for a matrix to be in RREF then the leading 1 must be the only entry in the column. Therefore, no other combination of rows would be able to produce that row. Furthermore, is the zero vector is applied to one of these rows, it could cause a linear combination is there is a non-zero value in the column of a leading 1. 

&#9989; **<font color=red>DO THIS:</font>** A computer program accepts a number of vectors in $\mathbb R^3$ as input and checks to see if the vectors are linearly independent and outputs a True/False statment. 
Discuss in your groups, which is more likely to happen due to round-off error--that the computer states that a given set of linearly independent vectors is linearly dependent, or vice versa? 
Put your thoughts below.

It would more often for the computer to output True for linearly independent becuase in order for the rit to input false the linear combination must equal the original row. Die to round off error, if they do not exactly equal each other, the computer will confirm that they are linearly independent. 


---
<a name=Subspaces></a>
## 5. Subspaces

A **Subspace** of a vector space $V$ is a subset $S\subset V$ that is a vector space under the same operations "$+$" and "$\cdot$" of $V$.

### Subspace Theorem

> A subset $S$ of a vector space $V$ is a vector space under the same operations "$+$" and "$\cdot$" of $V$, provided:
>
>1. $S$ is nonempty,
>2. $S$ is closed under the operations "$+$" and "$\cdot$".



&#9989; **<font color=red>DO THIS:</font>** Consider the space of all cubic polynomials:
$$P_3=\left\{a+bx+cx^2+dx^3\;\middle|\; a,b,c,d\in\mathbb{R}\right\}.$$
Is the set of all linear polynomials
$$S=\left\{a+bx\mid a,b\in\mathbb{R}\right\}$$
a subspace of $P_3$? If so, show that the conditions of the Subspace Theorem are satisfied. If not, why? (Is it not a subset? Is it not a vector space?)

Yes, this is a subspace because of the condition where $c = d = 0 \in P_3$.<br/>

The 0 vector is in S, trivially where $a=b=0$.

let $a,b,c,d \in \mathbb{R}$ consider $(b + a*x) + (d + c*x) = (b+d) + (a + c)*x$<br/>
Because $a+c \in \mathbb{R}$ and $b+d \in \mathbb{R}$, $(a*x+b) + (c*x+d) \in S$

Let $a,b,k \in \mathbb{R}$ Then $k*(a + b*x) = k*a + k*b*x$<br/>
Because $k*a \in \mathbb{R} $ and $ k*b \in \mathbb{R}$ <br/> $k*(a + b*x) \in S$



&#9989; **<font color=red>DO THIS:</font>** Consider the space of all real $2\times2$ matrices:
$$
\mathbb{R}^{2\times2} = \left\{\left[
\begin{matrix}
    a & b \\
    c & d
\end{matrix}
\right]\;\middle|\;a,b,c,d\in\mathbb{R}\right\}.
$$
Is the set of all $2\times2$ invertible matrices
$$S = \left\{A\in\mathbb{R}^{2\times2}\;\middle|\;\mathop{\det}(A)\neq0\right\}$$
a subspace of $\mathbb{R}^{2\times2}$? If so, show that the conditions of the Subspace Theorem are satisfied. If not, why? (Is it not a subset? Is it not a vector space?)

Yes this is a subspace, with $a = d = 1$ and $c = b = 0$

What about the set of all $2\times2$ diagonal matrices
$$
S = \left\{\left[
\begin{matrix}
    a & 0 \\
    0 & b
\end{matrix}
\right]\;\middle|\;a,b\in\mathbb{R}\right\}?
$$
Is this a subspace of $\mathbb{R}^{2\times2}$? If so, show that the conditions of the Subspace Theorem are satisfied. If not, why? (Is it not a subset? Is it not a vector space?)

Yes, this is a subspace because of the condition where $c = d = 0 \in \mathbb{R}$.<br/>

The identity matrix is in S, trivially where $a=b=1$.

let $a,b,c,d \in \mathbb{R}$ consider 

$$
\left[
\begin{matrix}
    a & 0 \\
    0 & b
\end{matrix}
\right]
+
\left[
\begin{matrix}
    c & 0 \\
    0 & d
\end{matrix}
\right]

=

\left[
\begin{matrix}
    a+c & 0 \\
    0 & b+d
\end{matrix}
\right]
$$

Because $a+c \in \mathbb{R}$ and $b+d \in \mathbb{R}$ this is closed under addition.

Let $k\in \mathbb{R} $ <br/>$k * \left[
\begin{matrix}
    a & 0 \\
    0 & b
\end{matrix}
\right] = \left[
\begin{matrix}
    ka & 0 \\
    0 & kb
\end{matrix}
\right] $

Because $ka \in \mathbb{R}$ and $kb \in \mathbb{R}$ this is closed under multiplication.


&#9989; **<font color=red>DO THIS:</font>** Consider the vector
$$
\vec{v} = \left[
\begin{matrix}
    -1 \\
    2  \\
    1
\end{matrix}
\right].
$$
Is the set
$$S = \left\{\vec{x}\in\mathbb{R}^3\;\middle|\; \vec{x}\cdot\vec{v}=0\right\}$$
of all vectors in $\mathbb{R}^3$ that are orthogonal to $\vec{v}$ a subspace of $\mathbb{R}^3$? If so, show that the conditions of the Subspace Theorem are satisfied. If not, why? (Is it not a subset? Is it not a vector space?)

----
Written by Dr. Dirk Colbry, Michigan State University
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=eddc04b2-32a0-43fc-87cf-17e6670be569' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>