## Put the names of all group members present today below:

Kaitlyn Watson, Jacob Miller, Christian Lulaj, David Robbins,Haobo.Liu

# 13 In-Class Assignment: Change of Basis

<img alt="Change of basis visualization" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Vector_components_and_base_change.svg/200px-Vector_components_and_base_change.svg.png" width="25%">

Image from: Wikimedia



### Objectives
1. Be able to determine a transition matrix that converts the components of a vector in the standard basis to those in a different basis $B_1$.
1. Be able to determine a transition matrix that converts the components of a vector in (non-standard) basis $B_1$ to the standard basis.
1. Determine a transition matrix that converts a vector between two bases $B_1$  and $B_2$. 
1. Be able to explain why for a Markov Matrix $A$, $A^nv$ converges to a multiple of the steady state.


In [ ]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

# import for checking answers
from answercheck import checkanswer

----
<a name="Ex1"></a>
## 1. Change of Basis - Example 1

Recall that the standard basis in $\mathbb R^2$ is given by
$$
\vec{e}_1=\left(\begin{array}{r}
1\\
0
\end{array}
\right),\,\,\,\,\,
\vec{e}_2=\left(\begin{array}{r}
0\\
1
\end{array}
\right).
$$

Consider three column vectors:
$$
\vec{b}_1=\left(\begin{array}{r}
1\\
1\end{array}
\right),\,\,\,\,\,
\vec{b}_2=\left(\begin{array}{r}
2\\
4
\end{array}
\right).
$$

&#9989;  **<font color=red>QUESTION:</font>** \
Form a $2\times2$ (numpy) matrix $B$ whose columns are the vectors $\vec{b}_1$ and $\vec{b}_2$.

In [ ]:
# Put your answer to the above question here

B=np.matrix([[1,2], [1,4]])

In [ ]:
checkanswer.matrix( B, '9ef7fffdd71c6e7715c345ec28aeee0f' );


    Trying to convert to float using ```A = A.astype(float)```.

Testing [[1. 2.]
 [1. 4.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION:</font>** 
Check that vectors are linearly independent, i.e. they can form a basis.

In [ ]:
# Put your answer to the above question here

#if the determinant in non-zero, then it forms a basis

det=np.linalg.det(B)
print(det)

B_inv=np.linalg.inv(B)

print(B_inv)

2.0
[[ 2.  -1. ]
 [-0.5  0.5]]


&#9989;  **<font color=red>QUESTION:</font>** 
Consider a point whose coordinates in the standard basis are $(3,2)^T$. Calculate its coordinates in the basis of $\vec{b}_1$ and $\vec{b}_2$. Store the result in variable `ub`.

In [ ]:
# Put your answer to the above question here

u=np.matrix([[3], [2]])

ub=B_inv*u
ub

matrix([[ 4. ],
        [-0.5]])

In [ ]:
checkanswer.matrix( ub, '6a556cde9d129145fc84542f5fa623fd' );

Testing [[ 4. ]
 [-0.5]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION:</font>** 
Consider a point whose coordinates in the $(\vec{b}_1, \vec{b}_2)$ basis are $(5,7)^T$. Calculate its coordinates in the standard basis. Store the result in variable `u`.

In [ ]:
# Put your answer to the above question here
u_b = np.matrix([5,7]).T
u = B * u_b

In [ ]:
checkanswer.matrix( u,  'a0f5d18547c5adc3810a04695105db3b');


    Trying to convert to float using ```A = A.astype(float)```.

Testing [[19.]
 [33.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION:</font>** 
Consider a point whose coordinates in the $(\vec{b}_1, \vec{b}_2)$ basis are $(5,7)^T$. Calculate its coordinates in the basis given by
$$
\vec{v}_1=\left(\begin{array}{r}
1\\
-1\end{array}
\right),\,\,\,\,\,
\vec{v}_2=\left(\begin{array}{r}
2\\
2
\end{array}
\right).
$$

Store the result in variable `uv`.

In [ ]:
# provide your answer here

V=np.matrix([[1,2], [-1,2]])

V_inv=np.linalg.inv(V)

u=np.matrix([[5],[7]]).T

uv=V_inv*B*u

uv

matrix([[-7.],
        [13.]])

In [ ]:
checkanswer.matrix( uv, '630589d0210ba72be9cde5a17eebc7af');

Testing [[-7.]
 [13.]]
Answer seems to be correct



----
<a name="Ex2"></a>
## Example 2 - Coordinates in a rotated basis

Note that in physics, robotics, etc. we often need to change our frame of reference, i.e. change the coordinate system we are using. In the questions below we consider two coordinate systems rotated with respect to each other.

Rotate the $xy-$axes in the plane counterclockwise through an angle  $\theta = 60^{\circ}$ to obtain new $x'y'$-axes. Use the methods above to answer the following two questions.

&#9989;  **<font color=red>QUESTION:</font>** Find the $x'y'$-coordinates of the point whose $xy$- coordinates are $(3,2)$. Store your answer in a variable `rprime`.

In [ ]:
# provide your answer here
coord = np.matrix([[3, 2]]).T

theta = 60 * np.pi / 180.0

rotation = np.matrix(([np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]))
rotation_inv = np.linalg.inv(rotation)

rprime = rotation_inv*coord

In [ ]:
checkanswer.matrix( rprime, '966d4c3604f84708413ae2d25c289755');

Testing [[ 3.23205]
 [-1.59808]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION:</font>** Find the $xy$-coordinates of the point whose $x'y'$- coordinates are $(4,-4)$. Store your answer in a variable `r`.

In [ ]:
# provide your answer here

coord2=np.matrix([[4], [-4]])

r=rotation*coord2

r

matrix([[5.46410162],
        [1.46410162]])

In [ ]:
checkanswer.matrix( r, '5265b74a4b1a858fdfebb6ae5e7bd6b4');

Testing [[5.4641]
 [1.4641]]
Answer seems to be correct



# 2 Fundamental spaces

<img alt="Alternative visual representation showing how the four Fundamental Subspaces spaces map to each other" src="https://upload.wikimedia.org/wikipedia/commons/4/4c/KerIm_2015Joz_L2.png" width="30%">

Image from: [wikipedia](https://en.wikipedia.org/wiki/Kernel_(linear_algebra))

> *Row space of $A$*, $\mathcal R(A)$: linear combination of all rows of $A$

> *Column space of $A$*,  $\mathcal{C}(A)$: linear combination of all columns of $A$

> *Null space or kernel of $A$*, $\mathcal{N}(A)$: all $x$ such that $Ax=0$

> *Null space of $A^\top$*, $\mathcal{N}(A^\top)$: all $y$ such that $A^\top y =0$

Discussion on how to find the fudamental spaces for a given matrix, especially if it is not already in RREF. Note - in the pre-class assignment the matrix was in RREF. Pay special attention to finding a basis for $\mathcal C(A)$. Related to Question 3 below, be sure to discuss why we are finding RREF of $A^T$ in order to find a basis for $\mathcal C(A)$ and why the pivot columns of rref(A) do not necessarily give a basis for $\mathcal C(A)$, if $A$ is not in RREF.

<img alt="Classic picture of the four fundamental spaces. Please see text for detailed description." src="https://kevinbinz.files.wordpress.com/2017/02/linear-algebra-fundamental-space-interpretation-6.png" width="90%">

Image from: https://kevinbinz.com/2017/02/20/linear-algebra/

Consider the following matrix $A$. 

$$ 
\left[
\begin{matrix}
    1 & 0 & 3  \\
    0 & 1 & 5  \\
    1 & 1 & 8 
\end{matrix}
\right] 
$$

&#9989; **<font color=red>QUESTION 1:</font>** What is the reduced row echelon form of $A$?

In [ ]:
A=np.matrix([[1,0,3], [0,1,5], [1,1,8]])

rref=sym.Matrix(A).rref()[0]
rref = np.matrix(rref, dtype=float)
rref

matrix([[1., 0., 3.],
        [0., 1., 5.],
        [0., 0., 0.]])

In [ ]:
from answercheck import checkanswer

checkanswer.matrix(rref,'1731818a1555cc33a778a4eb76af945c');


    Trying to convert to a array matrix using ```A = np.matrix(A)```.


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[1. 0. 3.]
 [0. 1. 5.]
 [0. 0. 0.]]
Answer seems to be correct



**ROW SPACE** The first and second (non zero) rows of the above matrix "spans" the same space as the orignal three row vectors in $A$. We often call this the "row space" and it can be written as a linear combination of the non-zero rows of the reduced row echelon form:

$$row(A) = \{r(1,0,3)^\top+s(0,1,5)^\top\} = \operatorname{span}((1,0,3)^\top,(0,1,5)^\top)$$

&#9989; **<font color=red>DO THIS:</font>** Calculate  the solutions to the system of homogeneous equations $Ax=0$. This is often called the **NULL SPACE** or sometimes **KERNEL** of $A$.

In [ ]:
RREF=sym.Matrix(rref)
RREF

⎡1.0   0   3.0⎤
⎢             ⎥
⎢ 0   1.0  5.0⎥
⎢             ⎥
⎣ 0    0    0 ⎦

$x_1 + 3x_3 = 0$

$x_2 + 5X_3=0$

$x_3=x_3$


&#9989; **<font color=red>DO THIS:</font>** Calculate  a basis for the Null space of $A$.

$x_1 = -3t$

$x_2=-5t$

$x_3 = t$

so x=[-3t, -5t, t].T

or ([[-3],[-5],[1]])*t

so the basis: B=[-3,-5,1].T

&#9989; **<font color=red>DO THIS:</font>** We introduced two subspaces of $\mathbb R^3$. 
Pick one vector from the row space of $A$ and another vector from the null space of $A$. 
Find the dot product of these two vector.

In [ ]:
A=np.array([0,1,5])
B=np.array([-3,-5,1])

Dot_product=np.dot(A,B)
print(Dot_product)

0


&#9989; **<font color=red>QUESTION  2:</font>** Did you get the same value for the dot product as your neighbor (or if you are working by yourself, did you get the same value for the dot product if you made different choices for the representatives of the row space and null space of $A$)? Explain your answer.

yes, becuase the row space and the null space are perpendicular to each other. This means they are orthogonal and the dot product of a vector from each space is 0. They also both share the zero vector. We could have chosen any row vector with the null space vector.

### Expanding in an eigenbasis

Now imagine we are given a $2\times 2$ matrix $A$  with eigenvalues $\lambda_1$ and $\lambda_2$ and corresponding eigenvectors $u_1$ and $u_2$. Further assume that $\{u_1, u_2\}$ form a basis for $\mathbb R^2$. Recall that this means that $Au_1=\lambda_1 u_1$ and $Au_2=\lambda_2 u_2$. Then, $A^2u_1 = A(Au_1) = A(\lambda_1 u_1) = \lambda_1 (Au_1) = \lambda_1^2 u_1$.

&#9989;  **<font color=red>QUESTION:</font>** Using the above, give a simple formula for $A^nu_1$ and  $A^nu_2$ in terms of $\lambda_i$ and $u_i$ (noting that $u_1$ and $u_2$ are eigenvectors of $A$ with corresponding eigenvalues $\lambda_1$ and $\lambda_2$).

$A^nu_i=\lambda_i^nu_i$

**Note:** Now note that our Markov matrix (and this generally holds true) has an eigenvalue 1 and the other eigenvalue has absolute value less than 1. Let's say $\lambda_1=1$ and $|\lambda_2|<1$. This means that $\lambda_1^n = 1$ for any $n$.

&#9989;  **<font color=red>QUESTION:</font>** What do we know about $\lambda_2^n$ for large $n$?

$|\lambda_2^n| < 1$ It will be significantly small

**Note:** Now consider a vector $v\in \mathbb R^2$. Since $\{u_1, u_2\}$ form a basis for $\mathbb R^2$, we can express $v=au_1+bu_2$ for some scalars $a, b$. Note that we can say $(a,b)$ are the coordinates of $v$ in the eigenbasis of $A$.

&#9989;  **<font color=red>QUESTION:</font>** Find a formula for $A^nv$ in temrs of $n, a, b, \lambda_i, u_i$.

$A^n(au_i+bu_i)= \lambda^n (au_i+bu_i)$

&#9989;  **<font color=red>QUESTION:</font>** Based on the formula you provided for $A^nv$ (when $v$ was expanded in the eigenbasis), what does $A^nv$ approach as $n$ grows larger and larger, i.e. what happens in the long run? 

In the long run, becuase the first eigenvalue will be equal to one, the other eigenvalue will be significantly smaller, which means as n becomes larger and larger then lambda will approach zero

&#9989;  **<font color=red>QUESTION:</font>** Expand the vector $w0=(1,0)^T$ (the initial distribution of the polulation) in the basis of the eigenvectors of the transition matrix. Store the coordinates of $w0$ in the eigenbasis in a variable `w0B`

In [ ]:
#provide your answer here
w0 = np.matrix([[1],[0]])


[1. 0.]


In [ ]:
checkanswer.matrix(w0B, '1ce6459eb481ce381664b1542d6fa31a');


    Trying to convert to a array matrix using ```A = np.matrix(A)```.


    Trying to convert to float using ```A = A.astype(float)```.

Testing [[-1.]]
Answer seems to be incorrect



AssertionError: Answer is incorrect 6f5dfd4b64dcb175c6333134baa33247

&#9989;  **<font color=red>QUESTION:</font>** Calculate $\lambda_1^4 a u_1 + \lambda_2^4 b u_2$, where $(a,b)$ are the coordinates of $w0$ in the eigenbasis $u_1, u_2$. Based on the theoretical discussion above, explain the closeness of $A^4w_0$ and the steady state $u_1$. In this case what is $\lambda_2^4$?

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=eddc04b2-32a0-43fc-87cf-17e6670be569' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>